name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile main.tex
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Upload main.pdf
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: build/main.pdf
